### ISSUE TITLE
error in query.php

### ISSUE THREAD

**Issue by fabriciocosta** [ctmil/geostats-eulac#13]
[Mon Aug 10 16:59:31 2015] PHP Warning:  SQLite3::prepare(): Unable to prepare statement: 1, ambiguous column name: title in D:\0_DESARROLLO\1_MOLDEOINTERACTIVE
\0_desarrollo\Mapas EU-LAC\geostats-eulac\query.php on line 52
[Mon Aug 10 16:59:31 2015] PHP Fatal error:  Call to a member function bindValue() on boolean in D:\0_DESARROLLO\1_MOLDEOINTERACTIVE\0_desarrollo\Mapas EU-LAC\g
eostats-eulac\query.php on line 53
[Mon Aug 10 16:59:31 2015] ::1:50964 [500]: /query.php?type=keys&query=a - Call to a member function bindValue() on boolean in D:\0_DESARROLLO\1_MOLDEOINTERACTI
VE\0_desarrollo\Mapas EU-LAC\geostats-eulac\query.php on line 53

**Comment by csrocha** [comment]
Lo cierro porque creo que es un error duplicado.
