### ISSUE TITLE
Cluster color

### ISSUE THREAD

**Issue by fabriciocosta** [ctmil/geostats-eulac#17]
this is a specific cluster object, color should be in root object, not in every shape, or isnt ?
{
   "cls_id":2,
   "name":"Decrecimiento desempe\u00f1o industrial provincia de Argentina",
   "hint":null,
   "keywords":"Argentina;provincia;desempe\u00f1o;industria;Decrecimiento",
   "shapes":[
      {
         "shp_id":8574,
         "color":"#B20000"
      },
      {
         "shp_id":8572,
         "color":"#B20000"
      },
      {
         "shp_id":8582,
         "color":"#B20000"
      }
   ],
   "parent_clusters":[],
   "child_clusters":[]
}

**Comment by csrocha** [comment]
Resuelto.
