### ISSUE TITLE
Elaborar un color más adecuado para este tipo de indicador

### ISSUE THREAD

**Issue by fabriciocosta** [ctmil/geostats-eulac#46]
http://localhost:8000/?link_object=N4IgxgNgrgzgLgUwE4xALgNoCYCsBOAXQBoQYALAQwAcFVMCBfIA

No se aprecia el grafico, sigo pensando que deberíamos igualmente ponerle un bordecito, o pensar en la opcion de ver los colores como patrones.

**Comment by csrocha** [comment]
La idea es arreglarlo con la opacidad. Issue #23

**Comment by fabriciocosta** [comment]
No creo que sea suficiente... igual la opacidad es algo requerido. 
Otra idea para poner como enhancement: al hacer click en una region que si hay varios layers superpuestos, te muestre la lista de esos clusters y shapes (enhancement)

**Comment by csrocha** [comment]
Fabricio. No te concentres en este punto. El color ya fue aprobado.
