### ISSUE TITLE
Unificar el tipo de fonts

### ISSUE THREAD

**Issue by csrocha** [ctmil/geostats-eulac#52]
El font de la aplicación esta distribuido en varias partes del código y de los css. Esto hace difícil  probar rápidamente diferentes fonts. 

El objetivo es dejar la declaración de los fonts en un sólo archivo (css?) De forma que sea cómodo experimentar los fonts.

**Comment by csrocha** [comment]
Fabricio, los siguientes fonts no están unificados:

Menú
SVG

**Comment by fabriciocosta** [comment]
molgeo.css línea 41 y 46, unifica menú y svgs. En los svgs todo lo que sea <text>, sin embargo no se verá exactamente igual porque el motor que renderea el svg es ligeramente diferente... quizas pueda hacerse mejor pero no vale la pena ahora.

**Comment by fabriciocosta** [comment]
Perdon, ahora hago el commit que lo resuelve bien.
